name: service-build

on:
  push:
    branches: [main]
    paths:
      - service/**
      - .github/workflows/service**
  pull_request:
    branches: [main]
    paths:
      - service/**
      - .github/workflows/service**

defaults:
  run:
    working-directory: service

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
